name: otpauth_migration
description: A Dart package to encode and decode the otpauth-migration URI format used to import into and export 2FA secrets from the Google Authenticator app.
version: 0.0.7
repository: https://github.com/johncallahan/otpauth_migration

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  protobuf: ^2.0.1
  fixnum: ^1.0.0
  base32: ^2.1.3

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
